/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yanchunlan_changevoice_VoiceUtil */

#ifndef _Included_com_example_yanchunlan_changevoice_VoiceUtil
#define _Included_com_example_yanchunlan_changevoice_VoiceUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_yanchunlan_changevoice_VoiceUtil_MODE_NORMAL
#define com_example_yanchunlan_changevoice_VoiceUtil_MODE_NORMAL 0L
#undef com_example_yanchunlan_changevoice_VoiceUtil_MODE_LOLITA
#define com_example_yanchunlan_changevoice_VoiceUtil_MODE_LOLITA 1L
#undef com_example_yanchunlan_changevoice_VoiceUtil_MODE_UNCLE
#define com_example_yanchunlan_changevoice_VoiceUtil_MODE_UNCLE 2L
#undef com_example_yanchunlan_changevoice_VoiceUtil_MODE_THRILLER
#define com_example_yanchunlan_changevoice_VoiceUtil_MODE_THRILLER 3L
#undef com_example_yanchunlan_changevoice_VoiceUtil_MODE_FUNNY
#define com_example_yanchunlan_changevoice_VoiceUtil_MODE_FUNNY 4L
#undef com_example_yanchunlan_changevoice_VoiceUtil_MODE_ETHEREAL
#define com_example_yanchunlan_changevoice_VoiceUtil_MODE_ETHEREAL 5L
/*
 * Class:     com_example_yanchunlan_changevoice_VoiceUtil
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_yanchunlan_changevoice_VoiceUtil_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
